### ISSUE TITLE
Roadmap WIP

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#5749]
## New   components            
- [ ] Stack  P1  XL      #5419
- [ ] Text  P1  XL      #5386 
- [ ] Grid  P2  XL      #786
- [ ] Announcement  P2  L      #5615 
- [ ] Card/Box  P2  XL      #5322
- [ ] Collapsible Section  P2  L      #5736
- [ ] Form  P3  XL      #5582
- [ ] Pagination  P4  L  #349 
        
## Refactors            
- [ ] Button  P1  XL      
- [ ] List  P2  XL      
- [ ] Nav  P2  XL      
- [ ] Dropdown/ComboBox  P3  XXL      
- [ ] Breadcrumb  P3  XL      

## Code Cleanup   
- [ ] Accessibility Improvements P1 XL
- [ ] Remove unsupported lifecycle hooks   P2  L 
- [ ] Upgrading Dependencies  P3         
- [ ] Deprecated Props  P3         
- [ ] Portals  P3  M      
- [ ] Customizer/context  P3  S      
- [ ] ForwardRef  P3  M      
          
## Major Features            
- [ ] CloudPack  P1  XXL     
- [ ] Issue Bot  P1  XL      
- [ ] API Extractor  P2         
- [ ] Scoped Customizations  P2          
- [ ] Accessibility Scorecards  P2         
- [ ] Integrate Appveyor into production (Nick Pape)  P2         
- [ ] Use Text Component  P3  XL      
- [ ] Localization (string file)  P4         
- [ ] Repackaging (split OUFR up) P4         
- [ ] Create Fabric App  P4

**Comment by micahgodbolt** [comment]
moved this to wiki
