### ISSUE TITLE
Theming: Schemes & Improved Performance

### ISSUE THREAD

**Issue by JasonGore** [OfficeDev/office-ui-fabric-react#5979]
## Component Details

This is a placeholder for Theming improvements around schemes and improved performance. These improvements have the following goals:

| Goal      | Rationale     | Goal Currently Met | Status | PR |
|-----------|----------|----------|--------|-----|
| Support for schemes that allow multiple themes to coexist in global and local context.  (See #5480) | Eliminate the need of having to pepper code with multiple `Customizers`. | :white_check_mark: | | #6391, #6854 
| Increase developer awareness of theming and schemes and impact on current and new component designs. | Make sure existing and new components work well with themes and schemes. |  :white_check_mark: | | #6669 
| Create Theme Provider component that's easy to use with simple props such as a theme object and scheme name. | Make using themes as easy as possible. | :white_check_mark: | | #6854 |

### Code mockup/example

__Code Sample__

```

```

### Component Ownership
This will be a core Fabric package with initial implementation and support provided by the core Fabric team (main POC @JasonGore.)

## TODOs
| TODO      | Complete     | PR |
|-----------|----------|-------------|
| Resolve #6391 TODOs regarding scheme default init, variant package folding, and scheme processing on every render. | :x: | |

## Steps

- [ ] is themable (base/styles)
- [ ] has unit tests
- [ ] has snapshot tests
- [ ] has visual tests
- [ ] has documentation and examples
- [ ] Design Review
- [ ] API review
- [ ] Public Preview
- [ ] Ready for Publishing

**Comment by levithomason** [comment]
Awesome.

Another aspect to this is isolating ourselves from framework churn and supporting other frameworks right now (angular, vue, vanilla, etc).  This is not only a long term goal of our shared Stardust UI effort, it is also an immediate goal for some teams at Microsoft.

Since framework agnostic accessibility, styling, and state are at the heart of Stardust UI and both Semantic UI React and Office UI Fabric React are targeting convergence there, I think it would be superb if we could collaborate on a shared Stardust styling mechanism that powered all our components and enabled other frameworks to utilize the same mechanism.

This probably warrants some offline planning to get the big picture worked out, but I think it is well deserved.  If we can get this going, it will really set us up for more convergence moving forward.  It should also help inform our theming story.  Finally, I hope it can also address some of the perf concerns around CSS in JS.
 
Thoughts?

**Comment by levithomason** [comment]
Anyone here know about / keeping tabs on https://github.com/Microsoft/fast-dna?  This seems to be a shared mission that on the surface sounds identical to many Stardust ideas.

**Comment by JasonGore** [comment]
I've moved all unfinished items to children of #6978 (and specifically added Levi's comment to #6989), so I will close this issue as resolved.
