### ISSUE TITLE
Fabric 7.0 Planning

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#7023]
[Project: 7.0 Release](https://github.com/OfficeDev/office-ui-fabric-react/projects/29)

[View and try `fabric@next` builds on *Fabric React Demos*](https://fabricweb.z5.web.core.windows.net/oufr/7.0.0-alpha010/)

# Cross-project tasks

## Upgrades
* [X] Upgrade to React 16.8.3 - #8041
* [X] Upgrade to TypeScript 3.3.3 - #8040 

## Theming
* [x] Default to Fluent theme - #8038 - In progress (27/42)

## Packages

* [X] Create "legacy" package - #8626

## Deprecation

* [ ] Remove use of deprecated lifecycle methods - #8743
* [x] Use new context API - #7365 #7364 #7366 #7368

## API

* [ ] Modify slots API - #8328

# Targeted fixes

## Controls

* [X] Slider: Remove deprecated types and make controllable - #8576
* [X] Nav: Move to legacy package - #8627

## Testing

* [X] Validate test debugging in fabric 7

# Cut
* ~Remove deprecated APIs~ - #8042 - pushed to next release
* ~Separate base theme into own package~ - #8039 - wontfix

**Comment by lafe** [comment]
If you increase the minimum versions like that, please ensure that the SharePoint Framework also supports these versions (On Premises and Online). Currently, SPFx uses React 16.3 and TypeScript 2.4.2.

**Comment by MLoughry** [comment]
Is there an issue tracking not using hard-coded colors in a few of the Fluent styles (eg., [DefaultButton](https://github.com/OfficeDev/office-ui-fabric-react/blob/157286e51909c905cd1c3747d92d4c6102f92121/packages/fluent-theme/src/fluent/styles/DefaultButton.styles.ts#L18)). 

This is currently a blocker for Outlook Web even dogfooding Fluent themes. Fluent should not be made the default in 7.0 so long as this is still an issue.

**Comment by micahgodbolt** [comment]
@Vitalius1 are you familiar with those fluent styles?

**Comment by Vitalius1** [comment]
@micahgodbolt #8098 should solve all the issues @MLoughry mentioned.

**Comment by khmakoto** [comment]
Closing this as Fabric 7.0 has been out for a while.
