### ISSUE TITLE
Jan-March 2019 Roadmap

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#7402]
(WIP)

Fabric is an open source project with contributions coming from numerous sources around and outside of Microsoft. The Fabric Team©®™℠ is an Office funded group dedicated to improving the Fabric platform through various initiatives. These are our current focuses for the upcoming quarter. 

## Theming
Lead: @JasonGore  
Meta issue can be found at  #6978

The main objective is to create a unified approach to theming and customization that can be used across all of the Fabric controls as well as controls built on top of, or to be used in conjunction with Fabric.

Primary objectives currently include:

- [x] Slots #7308
- [x] Theme Tokens
- [ ] Typography
- [x] Theme Provider

## Abstracting Build Process (just) #7415
Lead: @kenotron
 We're moving our build scripts into a package that will be shared across existing and future repos. 

- [ ] Create just-stack-web-lib
- [ ] Create 'outdated' and 'selfupdate' 

## GitHub Bot 
Leads: @cliffkoh @kkjeer 
Our officeui-bot is already a huge help to our repo, and we're planning to continue to invest in the bot platform this upcoming quarter. Our goal is to create a platform that will support our bot working in any partner repo.

## Fabric 7.0 Prep 
Lead: @ecraig12345 

- [ ] Clean up deprecated lifecycle hooks #4613
- [ ] Make controlled/uncontrolled behavior more consistent

## New Controls
- [ ] Left Nav #6221  
- [x] Stack #5419 
- [x] Text
- [x] Button in Experiments #6134 
- [x] Toggle in Experiments
- [ ] Pagination
- [ ] Collapsible Section #5736 

## Updated Controls
- [x] Pickers in CSS in JS #5411
- [ ] Merge/Refactor Combobox and Dropdown #6030
- [ ] Remove the Shimmer from experiments #8020 

## Fluent Controls
TBA

## Improve Documentation
Theming
Component Creation
Icons
