### ISSUE TITLE
Default to Fluent theme

### ISSUE THREAD

**Issue by jdhuntington** [OfficeDev/office-ui-fabric-react#8038]
# Fluent by Default
## Overview
For the 7.0 release, we'll be switching the default styling for Fabric React from MDL2 to Fluent, using the [@uifabric/fluent-theme](https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/fluent-theme) as the base. We will strive to keep the delta between @uifabric/fluent-theme and the default 7.0 Fluent styles as minimal as possible.

At a high level, this effort will be covered by two projects:

1. Applying Fluent styles to the default styles in [@uifabric/styling](https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/styling/src/styles).
2. Applying Fluent styles to all [office-ui-fabric-react](https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/office-ui-fabric-react/src/components) components. [Here](https://microsoft.sharepoint.com/teams/FabricTactical/_layouts/OneNote.aspx?id=%2Fteams%2FFabricTactical%2FSiteAssets%2FFabricTactical%20Notebook&wd=target%28Knowledge.one%7CF8BBBA8D-F64F-2349-A88A-46458A3C3D7B%2FFluent%20styles%20moving%7CC92B7BBB-F60C-E84B-A17A-396794262606%2F%29onenote:https://microsoft.sharepoint.com/teams/FabricTactical/SiteAssets/FabricTactical%20Notebook/Knowledge.one#Fluent%20styles%20moving&section-id={F8BBBA8D-F64F-2349-A88A-46458A3C3D7B}&page-id={C92B7BBB-F60C-E84B-A17A-396794262606}&end) is link to some steps to follow and what pitfalls you might encounter if tackling some of the components.

We'll keep a log here of any issues to watch out for when upgrading from Fabric 6, whether or not you're using the Fluent theme. Note that the existing MDL2 styles will only be available on Fabric 6.x and **will not be retained in Fabric 7**.

To make sure your app will be ready for the new Fluent styles, we strongly encourage you to start using @uifabric/fluent-theme now.

## Design Language
This project will involve updating the base global styles used by components and exposed by the @uifabric/styling package.

1. Colors
     - [x] Map the new warmer neutrals from [`FluentTheme`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/fluent-theme/src/fluent/FluentTheme.ts) to the [`DefaultPalette`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/styling/src/styles/DefaultPalette.ts#L4). **Done here:** #8148 
     - [ ] Expose the various new [color "palettes"](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/fluent-theme/src/fluent/FluentColors.ts) from the Fluent theme, e.g. `CommunicationColors`, `NeutralColors`, and `SharedColors`, as part of the [styling package](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/styling). **This part of moving the colors needs further investigation by design team.**

2. Depth
     - [x] Expose the new [Fluent depth levels](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/fluent-theme/src/fluent/FluentDepths.ts) in [`DefaultEffects`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/styling/src/styles/DefaultEffects.ts#L3). **Done here:** #8148

3. Motion
     - [ ] Expose the new new [Fluent motion functions](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/fluent-theme/src/fluent/FluentMotion.ts) in [`AnimationStyles`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/styling/src/styles/AnimationStyles.ts). **Motion is planned to be last after everything else is done**

4. Typography
     - [x] Reconcile [Fluent "palette" font sizes](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/fluent-theme/src/fluent/FluentType.ts) with [existing "semantic" font sizes](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/styling/src/styles/fonts.ts#L71). **Done here:** #8801 

## Components
This project will involve mixing in each component's Fluent styles into its corresponding default *styles.ts definition. For example, Breadcrumb's [Fluent styles](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/fluent-theme/src/fluent/styles/Breadcrumb.styles.ts) will be mixed into its [base styles](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.styles.ts).

As a **stretch goal**, we will evaluate styles that can be extracted as component [tokens](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Slots-&-Tokens) for enhanced customization. We likely won't expose those for the 7.0 release, though—we'll likely save most of them for a future release that can include tokens comprehensively.

Below are the components that we're targeting for the 7.0 "Fluentization".

### Basic Inputs
- [x] Button (@Vitalius1 )
  - Note that we will likely try to promote the [experimental Button](https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/experiments/src/components/Button) to replace the existing one, so Fluent styles will be ported after that's complete. **Decided to invest some time and fluentize the current button as it adds too much noise to screener tests because it's used in so many examples**

- [x] Checkbox (@Vitalius1 )
- [x] ChoiceGroup (@Vitalius1 )
- [x] ComboBox (@Vitalius1 )
  - Outstanding issue: #8584
- [x] ContextualMenu (@Vitalius1 )
- [x] Dropdown (@Vitalius1 )
  - Outstanding issue: #8584
- [x] Label (@Vitalius1 )
- [x] Link (@Vitalius1 )
- [x] Rating (@Vitalius1 )
- [x] Slider (@Vitalius1 )
- [x] SpinButton (@Vitalius1 )
- [x] TextField ( @Vitalius1 )
- [x] Toggle (@Vitalius1 )
- [ ] Polish pass

### Navigation
- [x] Breadcrumb (@Vitalius1 )
- [x] CommandBar (@Vitalius1 )
- [ ] Nav
  - **Need to confirm design changes.** There is a new design for a successor side nav control that's represented in the toolkits, and which includes much more functionality than the existing Nav control (used mostly in SharePoint Document Libraries). Since the experimental SideBar control is much closer to the intended Fluent design, we'd like to leave the current Nav control as-is without any changes besides semantic color updates. Further, it's likely a candidate for the proposed [legacy components package](https://github.com/OfficeDev/office-ui-fabric-react/issues/8626)
- [x] Pivot (@Vitalius1 )
- [ ] SearchBox
  - **Need to confirm status of design plans for SearchBox.** There is an effort for a comprehensive, updated search UX that may eventually result in a search box control that replaces the existing `SearchBox`. Since the status of that is currently unclear, we're not sure what changes may be required to make the existing `SearchBox` look and feel Fluent. This may include updated neutrals and rounded corners, but need to confirm.
- [ ] Polish pass

### Content
- [ ] ActivityItem
  - **Need to confirm design changes.** There are designs for this for product-specific scenarios, but need to confirm if they match the generic one in Fabric.
- [ ] Calendar
  - This will be tracked in #8698.
- [x] DetailsList (@Vitalius1 )
- [x] Facepile (@Vitalius1 )
- [x] GroupedList (@Vitalius1 )
- [x] Persona (@Vitalius1 )
- [ ] Polish pass

### Pickers
- [x] Pickers (@Vitalius1 )
- [x] ColorPicker (@Vitalius1 )
- [x] DatePicker (@Vitalius1 )
- [x] PeoplePicker (@Vitalius1 )
- [x] SwatchColorPicker (@Vitalius1 )
- [ ] Polish pass

### Progress & Validation
- [x] MessageBar (@Vitalius1 )
- [ ] Polish pass

### Surfaces
- [x] Callout (@Vitalius1 )
- [x] Dialog (@Vitalius1 )
- [x] HoverCard (@Vitalius1 )
- [x] Modal (@Vitalius1 )
- [x] Panel (@Vitalius1 )
- [x] TeachingBubble (@Vitalius1 )
- [ ] Coachmark
- [ ] Polish pass

**Comment by MLoughry** [comment]
Is there an issue tracking not using hard-coded colors in a few of the Fluent styles (eg., [DefaultButton](https://github.com/OfficeDev/office-ui-fabric-react/blob/157286e51909c905cd1c3747d92d4c6102f92121/packages/fluent-theme/src/fluent/styles/DefaultButton.styles.ts#L18)).

This is currently a blocker for Outlook Web even dogfooding Fluent themes. Fluent should not be made the default in 7.0 so long as this is still an issue.

**Comment by phkuo** [comment]
@MLoughry , @mikewheaton is tracking the issue and working with design to swap those to the correct colors.

Additional work:
1) All the changes in FluentTheme need to be rolled into the main OUFR project by default.
2) The new typography, rounded corners, and shadows/depth styles should be consumed from the theme.

**Comment by Jahnp** [comment]
FYI, I've updated @jdhuntington 's top comment with a detailed plan for how we're planning to address this project.

**Comment by abdullahsalem** [comment]
Thanks @jdhuntington for this helpful planning and organizing.

I am very interested to participate in this. However, I cannot access to the following resource:
>  [Here](https://microsoft.sharepoint.com/teams/FabricTactical/_layouts/OneNote.aspx?id=%2Fteams%2FFabricTactical%2FSiteAssets%2FFabricTactical%20Notebook&wd=target%28Knowledge.one%7CF8BBBA8D-F64F-2349-A88A-46458A3C3D7B%2FFluent%20styles%20moving%7CC92B7BBB-F60C-E84B-A17A-396794262606%2F%29onenote:https://microsoft.sharepoint.com/teams/FabricTactical/SiteAssets/FabricTactical%20Notebook/Knowledge.one#Fluent%20styles%20moving&section-id=%7BF8BBBA8D-F64F-2349-A88A-46458A3C3D7B%7D&page-id=%7BC92B7BBB-F60C-E84B-A17A-396794262606%7D&end) is link to some steps to follow and what pitfalls you might encounter if tackling some of the components.

I would be most grateful if you could help!

**Comment by gnanavelum** [comment]
is SideBar a component in Fabric 7.0? does it support all/most functionalities of Nav?

**Comment by jdhuntington** [comment]
@abdullahsalem Sorry for the late follow up! I have moved the content (sans screen shots) into this wiki entry: https://github.com/OfficeDev/office-ui-fabric-react/wiki/Fluent-Styles-Moving

We do have a majority of the components migrated at this point, but I believe there are a few that might still benefit from some touch-up; @Vitalius1 might be able to comment. Thanks for the offer!

**Comment by jdhuntington** [comment]
@gnanavelum `Nav` will still be available in the `@uifabric/legacy' package. As of yet, the `Sidebar` is not part of the official fabric 7 release and still lives in experiments. I believe that a sidebar/nav component resembling the experimental component will be released in a version of fabric 7, but likely not in the initial release. Does that work for your use-cases?
